## Reassignment dan Operasi Matematika pada Array
Mengubah Nilai/Data yang terdapat pada array
 1. Operasi matematika pada array tidak perlu selalu memiliki jumlah index yang sama / dimension yang sama
 2. manipulasi data bisa dilakukan karena array adalah mutable
 3. untuk reassignment perlu mencari index data / index array nya utk mengubah data

In [ ]:
import numpy as np
arr_contoh = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

arr_duplicate = arr_contoh.copy()

# Reassignemnt data pada array
  # ambil index nya, lalu uabha data nya
arr_duplicate[0,0] = 100
print(arr_duplicate[0,0])

# Reassignment beberapa data
arr_duplicate[1] = 200
print(arr_duplicate)

print("yang contoh", arr_contoh)

In [ ]:
import numpy as np
# Operasi Matematika dalam Array
# 1. perkalian
arr_perkalian = arr_contoh * 2
print(arr_perkalian)

# 2. pembagian
arr_pembagian = arr_contoh / 2
print(arr_pembagian)

# 3. pertambahan
arr_pertambahan = arr_contoh + 10
print(arr_pertambahan)

#  4. Pertambahan dengan sesama array
arr_contoh2 = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

arr_pertambahan_array = arr_contoh + arr_contoh2
print(arr_pertambahan_array)

In [ ]:
# Tugas
# arr_contoh akan ditambahkan 1, 2, 3 dari arr_contoh[0], di tiap index sesuai urutan
  # hasil yang di harapkan : 
  # [[ 2  4  6]
  #  [ 5  7  9]
  #  [ 8 10 12]]


# penyelesaian bisa dengan 2 cara
# cara 1 dengan mengbail data dari dalam nya
arr_tugas1 = arr_contoh + arr_contoh[0]
print(arr_tugas1)

# cara 2 dengan membuat array baru
  # cara ini membuktikan operasi matematika bisa berbeda dimension juga
import numpy as np
arr_1_dimension = np.array([1,2,3])
arr_tugas_2 = arr_contoh + arr_1_dimension
print(arr_tugas_2)
