# Latihan NumPy Array

### 1. import numpy

In [1]:
# ketik kode kalian di dalam cel ini
import numpy as np

### 2. Buatkan array dari 1 sampai 4

In [2]:
# ketik kode kalian di dalam cel ini
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
# hasil output yang diinginkan:

array([1, 2, 3, 4])

### 3. Buatkan array dengan 10 elemen bernilai 0

In [3]:
# ketik kode kalian di dalam cel ini
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# hasil output yang diinginkan:

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 4. Buatkan array dengan ukuran 5x5 bernilai 1 semua

In [4]:
# ketik kode kalian di dalam cel ini
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# hasil output yang diinginkan:

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### 5. Buatkan array dengan ukuran 10x20 bernilai 24

In [ ]:
# ketik kode kalian di dalam cel ini
    # pakai np.ones lalu dikali 20 yang membuat semua data jadi 20
arr = np.ones((10,20))*20
# call arr nya
arr

array([[20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.,
        20., 20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.,
        20., 20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.,
        20., 20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.,
        20., 20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.,
        20., 20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.,
        20., 20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.,
        20., 20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.,
        20., 20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 2

In [ ]:
# hasil output yang diinginkan:

array([[20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.,
        20., 20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.,
        20., 20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.,
        20., 20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.,
        20., 20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.,
        20., 20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.,
        20., 20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.,
        20., 20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.,
        20., 20., 20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 2

### 6. Buatkan array dengan elemen bilangan genap dari 1 sampai 100 (100 tidak termasuk)

In [23]:
# ketik kode kalian di dalam cel ini
np.arange(2,100,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [ ]:
# hasil output yang diinginkan:

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [8]:
# Perhatikan array berikut ini
arr_latihan = np.arange(1,37).reshape(6,6)
arr_latihan

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

### 7. Berdasarkan arr_latihan, lakukan indexing sehingga mendapatkan hasil berikut ini:

In [9]:
# ketik kode kalian di dalam cel ini
print(arr_latihan[3,-1])

24


In [ ]:
# hasil output yang diinginkan:

24

In [10]:
# ketik kode kalian di dalam cel ini
print(arr_latihan[2,-1])

18


In [ ]:
# hasil output yang diinginkan:

18

### 8. Berdasarkan arr_latihan, lakukan slicing sehingga mendapatkan hasil berikut ini:

In [11]:
# ketik kode kalian di dalam cel ini
arr_latihan[2]

array([13, 14, 15, 16, 17, 18])

In [ ]:
# hasil output yang diinginkan:

array([13, 14, 15, 16, 17, 18])

In [12]:
# ketik kode kalian di dalam cel ini
arr_latihan[2:4]

array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [ ]:
# hasil output yang diinginkan:

array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [13]:
# ketik kode kalian di dalam cel ini
  # cari index array nya dulu (3:5), baru index data nya (3:5)
arr_latihan[3:5, 3:5]

array([[22, 23],
       [28, 29]])

In [ ]:
# hasil output yang diinginkan:

array([[22, 23],
       [28, 29]])

### 9. Ubah ukuran arr_latihan menjadi 1x36 dan 36x1

In [14]:
# ketik kode kalian di dalam cel ini
arr_latihan.reshape(1,36)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33, 34, 35, 36]])

In [ ]:
# hasil output yang diinginkan:

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33, 34, 35, 36]])

In [15]:
# ketik kode kalian di dalam cel ini
arr_latihan.reshape(36,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36]])

In [ ]:
# hasil output yang diinginkan:

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36]])

### 10. Berdasarkan array dibawah ini tentukan:

In [18]:
np.random.seed(24)
arr_random = np.random.randint(100, size=(10,10))
arr_random

array([[34,  3, 64, 87, 17, 17,  1, 79,  4, 99],
       [82, 11, 99, 15, 73, 18,  7, 25, 35, 95],
       [28,  0, 12, 95, 33,  1, 60, 55, 70, 97],
       [81,  6, 46, 65, 47, 89, 74, 35, 64, 27],
       [97, 33,  3,  4, 65, 10, 41, 56, 45,  7],
       [ 5, 60, 83, 42,  0, 27, 21, 66, 36, 54],
       [45, 96, 86, 34, 75, 94, 85, 39, 68, 63],
       [67, 71,  8, 67, 70, 23, 42, 74, 75, 80],
       [27, 65,  6, 32, 90, 98, 96, 24, 86, 44],
       [75, 62, 95, 12, 21, 42, 76, 35, 36, 38]], dtype=int32)

In [19]:
# ketik kode kalian di dalam cel ini
print(arr_random.max())

99


In [ ]:
# nilai maksimal

99

In [20]:
# ketik kode kalian di dalam cel ini
print(arr_random.min())

0


In [ ]:
# nilai minimal

0

In [21]:
# ketik kode kalian di dalam cel ini
print(arr_random.mean())

49.27


In [ ]:
# nilai rata-rata

49.27

In [22]:
# ketik kode kalian di dalam cel ini
print(arr_random.sum())

4927


In [ ]:
# nilai total

4927

# Selamat Telah Menyelesaikan Latihan Ini