## Catatan pribadi

## Fungsi Universal Pada Numpy
Numpy menyediakan Berbagai fungsi universal (ufuncs) yang melakukan operasi pada array. Fungsi-fungsi ini mencakup operasi 
  1. aritmatika, 
  2. trigonometri (berhubungan dng sudut, menghitung sudut --> sin, cos, tan), 
  3. logaritma (operasi matematika yang merupakan kebalikan dari eksponen (perpangkatan). Dalam kata lain, logaritma mencari nilai pangkat dari suatu bilangan pokok yang menghasilkan bilangan tertentu), 
  4. eksponensial ( Eksponen menunjukkan berapa kali suatu bilangan (disebut basis) dikalikan dengan dirinya sendir).
  5. dan banyak lagi bisa di cek di file nya di folder section 5 : 41.fungsi universal numpy

In [1]:
import numpy as np

arr_a = np.array([1,2,3])
arr_b = np.array([4,5,6])

In [2]:
# Fungsi statistik dalam numpy
arr_c = np.array([1,2,3,4,5,5])
# mean (rata - rata)
print(np.mean(arr_c))
#  median (nilai tengah)
print(np.median(arr_c))
# std (standar devisiasi) --> ukuran statistik yang menunjukkan seberapa tersebar atau bervariasinya suatu data dari nilai rata-ratanya (mean). Semakin kecil standar deviasi, semakin dekat data individu dengan nilai rata-rata, dan semakin homogen data tersebut.
print(np.std(arr_c))

3.3333333333333335
3.5
1.4907119849998598


In [3]:
# logaritma
np.log(arr_c)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.60943791])

In [4]:
# eksponensial
np.exp(arr_c)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 , 148.4131591 ])

In [5]:
# trigonometri
np.sin(arr_c)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.95892427])