# Fungsi Universal pada Numpy
NumPy menyediakan berbagai fungsi universal (ufuncs) yang melakukan operasi pada array. Fungsi-fungsi ini mencakup operasi aritmatika, trigonometri, logaritma, eksponensial, dan banyak lagi.

In [1]:
import numpy as np

### 1. Aritmetika

In [2]:
arr_a = np.array([1,2,3])
arr_b = np.array([4,5,6])

In [3]:
np.add(arr_a, arr_b)

array([5, 7, 9])

In [4]:
np.subtract(arr_a, arr_b)

array([-3, -3, -3])

In [5]:
np.multiply(arr_a, arr_b)

array([ 4, 10, 18])

In [6]:
np.divide(arr_a, arr_b)

array([0.25, 0.4 , 0.5 ])

### 2. Statistik

In [7]:
arr_c = np.array([1,2,3,4,5,5])

In [8]:
np.mean(arr_c)

3.3333333333333335

In [9]:
np.std(arr_c)

1.4907119849998598

In [10]:
np.median(arr_c)

3.5

### 3. Logaritma dan Eksponensial

In [11]:
np.log(arr_c)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.60943791])

In [12]:
np.exp(arr_c)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 , 148.4131591 ])

### 4. Trigonometri

In [13]:
np.sin(arr_c)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.95892427])

### FUNGSI-FUNGSI UNIVERSAL NUMPY

### Aritmatika

- `add`: Penjumlahan elemen-wise.
- `subtract`: Pengurangan elemen-wise.
- `multiply`: Perkalian elemen-wise.
- `divide`: Pembagian elemen-wise.
- `floor_divide`: Pembagian lantai elemen-wise.
- `negative`: Negasi elemen-wise.
- `power`: Perpangkatan elemen-wise.
- `remainder`: Sisa pembagian elemen-wise.
- `mod`: Alias untuk `remainder`.
- `fmod`: Sisa pembagian elemen-wise berbeda dengan `remainder`.

### Statistik

- `sum`: Penjumlahan elemen.
- `prod`: Perkalian elemen.
- `mean`: Rata-rata elemen.
- `std`: Standar deviasi elemen.
- `var`: Varians elemen.
- `min`: Nilai minimum.
- `max`: Nilai maksimum.
- `argmin`: Indeks dari nilai minimum.
- `argmax`: Indeks dari nilai maksimum.
- `median`: Nilai tengah elemen.
- `percentile`: Persentil elemen.
- `quantile`: Kuantilis elemen.

### Logaritma dan Eksponensial

- `exp`: Eksponensial elemen-wise.
- `expm1`: `exp(x) - 1` elemen-wise.
- `exp2`: Eksponensial basis dua elemen-wise.
- `log`: Logaritma natural elemen-wise.
- `log1p`: `log(1 + x)` elemen-wise.
- `log2`: Logaritma basis dua elemen-wise.
- `log10`: Logaritma basis sepuluh elemen-wise.

### Trigonometri

- `sin`: Sine elemen-wise.
- `cos`: Cosine elemen-wise.
- `tan`: Tangent elemen-wise.
- `arcsin`: Invers sine elemen-wise.
- `arccos`: Invers cosine elemen-wise.
- `arctan`: Invers tangent elemen-wise.
- `arctan2`: Invers tangent dari dua variabel elemen-wise.
- `hypot`: Panjang hypotenuse elemen-wise.
- `sinh`: Hyperbolic sine elemen-wise.
- `cosh`: Hyperbolic cosine elemen-wise.
- `tanh`: Hyperbolic tangent elemen-wise.
- `arcsinh`: Invers hyperbolic sine elemen-wise.
- `arccosh`: Invers hyperbolic cosine elemen-wise.
- `arctanh`: Invers hyperbolic tangent elemen-wise.

### Bitwise

- `bitwise_and`: AND bitwise elemen-wise.
- `bitwise_or`: OR bitwise elemen-wise.
- `bitwise_xor`: XOR bitwise elemen-wise.
- `invert`: Invers bitwise elemen-wise.
- `left_shift`: Left shift bitwise elemen-wise.
- `right_shift`: Right shift bitwise elemen-wise.

### Perbandingan

- `greater`: Lebih besar dari elemen-wise.
- `greater_equal`: Lebih besar atau sama dengan elemen-wise.
- `less`: Lebih kecil dari elemen-wise.
- `less_equal`: Lebih kecil atau sama dengan elemen-wise.
- `equal`: Sama dengan elemen-wise.
- `not_equal`: Tidak sama dengan elemen-wise.
- `logical_and`: AND logika elemen-wise.
- `logical_or`: OR logika elemen-wise.
- `logical_not`: NOT logika elemen-wise.
- `logical_xor`: XOR logika elemen-wise.

### Fungsi Floating-point

- `isfinite`: Memeriksa apakah elemen adalah finite.
- `isinf`: Memeriksa apakah elemen adalah infinity.
- `isnan`: Memeriksa apakah elemen adalah NaN (Not a Number).
- `signbit`: Memeriksa tanda bit elemen.
- `copysign`: Menyalin tanda dari satu elemen ke elemen lain.
- `nextafter`: Mengembalikan floating-point paling kecil yang lebih besar dari elemen pertama ke arah elemen kedua.
- `spacing`: Jarak antara elemen dan floating-point terdekat berikutnya.

### Fungsi Lainnya

- `absolute`: Nilai absolut elemen-wise.
- `fabs`: Nilai absolut floating-point elemen-wise.
- `rint`: Membulatkan ke integer terdekat elemen-wise.
- `sign`: Mengembalikan tanda dari elemen.
- `ceil`: Pembulatan ke atas elemen-wise.
- `floor`: Pembulatan ke bawah elemen-wise.
- `trunc`: Pemotongan desimal elemen-wise.
- `sqrt`: Akar kuadrat elemen-wise.
- `cbrt`: Akar kubik elemen-wise.
- `square`: Kuadrat elemen-wise.
- `clip`: Memotong nilai elemen-wise ke dalam rentang yang ditentukan.
- `deg2rad`: Konversi derajat ke radian elemen-wise.
- `rad2deg`: Konversi radian ke derajat elemen-wise.

Ini hanya beberapa dari fungsi universal yang tersedia di NumPy. Ada banyak lagi yang dapat ditemukan dalam dokumentasi resmi NumPy. Fungsi-fungsi ini sangat efisien dan dioptimalkan untuk operasi array, sehingga sangat membantu dalam berbagai aplikasi komputasi dan analisis data.