# Latihan Fungsi Universal Numpy

In [2]:
import numpy as np

In [3]:
# Perhatikan array berikut:
arr_a = np.array([2,3,2,1,5])
arr_b = np.array([2,5,5,7,9])

### 1. Dengan menggunakan fungsi universal, tampilkan hasil perkalian antara arr_a dan arr_b?

In [4]:
# ketik kode kalian di dalam cel ini
np.multiply(arr_a, arr_b)

array([ 4, 15, 10,  7, 45])

In [ ]:
# hasil output yang diinginkan:

array([ 4, 15, 10,  7, 45])

### 2. Berapakan selisih rata-rata antara arr_a dan arr_b?

In [5]:
# ketik kode kalian di dalam cel ini
#  1. rata rata kan setiap array dan masukan kedalam variabel
rata2_a = np.mean(arr_a)
rata2_b = np.mean(arr_b)

# 2. Kurangi hasil rata2 utk mencari selisih
hasil = rata2_a - rata2_b
#  3. panggil hasil
print(hasil)

-2.9999999999999996


In [ ]:
# hasil output yang diinginkan:

-2.9999999999999996

### 3. Berapakah selisih jumlah antara arr_a dan arr_b?

In [6]:
# ketik kode kalian di dalam cel ini
# 1. Sum setiap array
jumlah_a = np.sum(arr_a)
jumlah_b = np.sum(arr_b)

# 2. kurangi jumlah 
selisih_jumlah = jumlah_a - jumlah_b
# 3. panggil selisi jumlah
print(selisih_jumlah)

-15


In [ ]:
# hasil output yang diinginkan:

-15

In [7]:
# Perhatikan array berikut
nilai = [[70,45,56,66],[86,50,60,90],[90,75,84,93],[30,55,89,65]]
arr_nilai = np.array(nilai)
arr_nilai

array([[70, 45, 56, 66],
       [86, 50, 60, 90],
       [90, 75, 84, 93],
       [30, 55, 89, 65]])

### 4. Berapa nilai eksponential dari arr_nilai di baris ke 4 dan kolom ke 2?

In [8]:
# ketik kode kalian di dalam cel ini
print(np.exp(arr_nilai[3,1]))

7.694785265142018e+23


In [ ]:
# hasil output yang diinginkan:

7.694785265142018e+23

### 5. Berapa nilai selisih sinus dari total baris pertama dan cosinus dari total kolom pertama arr_nilai?

In [9]:
# ketik kode kalian di dalam cel ini
# question = selisis sinus dari total bari pertama (index o) - consinus total kolom pertama
# 1. cari total baris pertama
baris_1 = np.sum(arr_nilai,1)[0] #ini akan menjumlah secara horizontal karena axis nya 1
print(baris_1)


237


In [ ]:
# Total nilai baris pertama arr_nilai
# hasil output yang diinginkan:

237

In [10]:
# ketik kode kalian di dalam cel ini
# 2. cari total kolom pertama
kolom_1 = np.sum(arr_nilai, 0)[0] # ini akan menjumlah secara vertikal karena axis nya 0
print(kolom_1)

276


In [ ]:
# Total nilai kolom pertama arr_nilai
# hasil output yang diinginkan:

276

In [12]:
# ketik kode kalian di dalam cel ini
# 3. cari sin x sebagai sumbu x dari baris_1 sebagai garis hotizontal
data_sin = np.sin(baris_1)
# print(data_sin)
# 4. cari cosinus y sebagai sumbu y dari kolom_1 sebagai garis vertikal
data_cos = np.cos(kolom_1)
# print(data_cos)

total = data_sin - data_cos
print(total)

-1.8779422036551292


In [ ]:
# Selisih sinus x dan cosinus y
# hasil output yang diinginkan:

-1.8779422036551292