## Module Random
Numpy menyediakan modul numpy.random untuk menhasilkan angka acak. Modul ini sangat berguna dalam berbagai aplikasi seperti simulasi, statistik, machine learning dan lainya.

In [1]:
import numpy as np

### 1. Membuat angka random
    * .rand() = buat random dari 0 sampai 1 yang terdistirbusi uniform/seragam
    * .randn() = buat random yang terdistribusi normal, dengan rentang 0 - 1
    * .randint() = fungsi random yang bisa membuat angka random integer


In [2]:
# 1. .rand()
# 1 Dimension
print("1 dimension", np.random.rand(3)) # 3 = jumlah data
# 2 Dimension
print("2 dimension", np.random.rand(2,3)) # 2 = baris, 3 = jumlah data
# 3 Dimension
print("3 dimension", np.random.rand(4,3,5)) # 4 = baris, 3 = kolom, 5 = jumlah data

1 dimension [0.004655   0.99881462 0.33738895]
2 dimension [[0.43391218 0.80780817 0.92211197]
 [0.82002006 0.16384213 0.05016975]]
3 dimension [[[0.22669873 0.02175329 0.12257427 0.07830093 0.61668645]
  [0.06470667 0.86522759 0.51796062 0.19588859 0.79020021]
  [0.33775974 0.46731462 0.66243497 0.23067106 0.43682707]]

 [[0.02553518 0.20168305 0.52711326 0.69525518 0.51437114]
  [0.36562188 0.05961802 0.89505305 0.75789361 0.1065082 ]
  [0.98551539 0.46067616 0.68973967 0.57138036 0.18784143]]

 [[0.69254125 0.25035838 0.77797833 0.39170996 0.25650875]
  [0.45934674 0.28965871 0.24841708 0.71822762 0.66992075]
  [0.38263639 0.82446908 0.41014168 0.97138687 0.46699607]]

 [[0.46052307 0.00586899 0.24980364 0.25776601 0.58407356]
  [0.95440323 0.77120505 0.00109834 0.49809566 0.85868264]
  [0.04044552 0.74306356 0.02302878 0.66936251 0.76825213]]]


In [3]:
# 2. .randn()
# utk buat dimension nya sama seperti di rand di atas
np.random.randn(3)

array([ 0.40801831, -0.80419414,  0.40717621])

In [4]:
#3. .randint()
np.random.randint(1, 100, 20) #1 = angka start, 100 = angka terakhir, 20 = size -> jumlah data array

array([34, 15, 18, 62, 35, 95,  7, 69, 90, 14, 84, 86, 98, 76, 37, 88, 60,
       28, 29, 52], dtype=int32)

In [5]:
# Tugas
# bagaimana cara nya utk membuat angka random dengan dimension 2 dalam bentuk array 3x3 dari 1 - 100
np.random.randint(1,100, size=[3,3]) # cara 1
np.random.randint(1,100, (3,3)) # cara 2 dengan dibuat tuples
# np.random.randint?

array([[26, 69, 24],
       [84, 14,  3],
       [18, 83, 28]], dtype=int32)