### 2. Membuat Angka Random sesuai Distribusi
    # disini kita akan belajar mengatur parameter distribusi sesuai kebutuhan kita (lanjutan vidio 45)
    * nama_distribusi ==> keterangan parameter dalam distribusi
    * .uniform => low = angka rentang bawah, high = angka rentang atas nya, size = jumlah data dan dimension didalam array, bisa pakai tuples
    * .normal => loc = mean/rata2, scale = variasi nya, size = jumlah data dan dimensionn
    * .binomial => n = jumlah percobaan, p = probabilitas, size
    * .poisson => lambda , size


In [1]:
import numpy as np
# .uniform
np.random.uniform(0, 10, 10)

array([7.52483322, 5.16356185, 9.50488099, 5.00003939, 1.7559182 ,
       5.12870023, 5.60609782, 8.02229106, 5.03532386, 1.38544002])

In [2]:
# .normal
np.random.normal(loc=10, scale=10, size=(4,4))

array([[ 1.65813676, 10.3125754 , 13.77803508, 14.52042621],
       [ 4.67025838, 10.33741762,  7.70383662, 11.11881414],
       [23.43132826,  8.25266156, 10.84101387, 21.19038978],
       [11.78178847, 34.74767558, 17.56322987,  2.69473209]])

In [3]:
# .binomial
np.random.binomial(100, 0.5, 5)

array([44, 44, 49, 49, 51], dtype=int32)

In [4]:
# .poisson
np.random.poisson(40, 10)

array([30, 40, 55, 37, 38, 41, 32, 44, 43, 33], dtype=int32)