### 3. Random Seed (lanjutan video 45&46)
  * Dengan Random seed untuk mengunci angka random agar tidak berubah

In [1]:
import numpy as np
# 1. buat random seed untuk mengunci angka random
np.random.seed(1)
# 2. buat angka random nya menggunakan distrbusi yang diinginkan -> ini akan otomatis terkunci sesuai seed number nya
np.random.randint(1,10,(3,3))

array([[6, 9, 6],
       [1, 1, 2],
       [8, 7, 3]], dtype=int32)

In [2]:
import numpy as np
# 1. buat random seed untuk mengunci angka random
np.random.seed(2)
# 2. buat angka random nya menggunakan distrbusi yang diinginkan -> ini akan otomatis terkunci sesuai seed number nya
np.random.randint(1,10,(3,3))

array([[9, 9, 7],
       [3, 9, 8],
       [3, 2, 6]], dtype=int32)

In [3]:
# Tugas mencari sesuai video dengan dimension 4x4, dan terkunci di random seed
np.random.seed(7)
np.random.randint(1,100,(4,4))

array([[48, 69, 26, 68],
       [84, 24, 93, 58],
       [15, 24, 73, 90],
       [43, 91,  9, 40]], dtype=int32)