# Latihan Module Random Numpy

In [1]:
import numpy as np

### 1. Buatkan array dengan bilangan random integer ukuran 3x3 (nilai elemen tidak harus sesuai dengan solusi)

In [2]:
# ketik kode kalian di dalam cel ini
np.random.randint(1,100,(3,3))

array([[46, 32, 37],
       [37, 70, 41],
       [32, 78,  1]], dtype=int32)

In [ ]:
# hasil output yang diinginkan:

array([[ 1, 65, 33],
       [ 3, 18, 18],
       [63,  4, 31]])

### 2. Buatkan array dengan bilangan random terdistribusi normal, dengan mean=4 dan variance=10, dan ukuran 3x3 (nilai elemen tidak harus sesuai dengan solusi)

In [3]:
# ketik kode kalian di dalam cel ini
np.random.normal(loc=4, scale=10, size=(3,3))

array([[ -2.79869682, -10.58617175, -17.52459792],
       [  3.21590951,  -2.83027987,   5.51398691],
       [ 23.25477382,  -1.33783169,  -3.13406994]])

In [ ]:
# hasil output yang diinginkan:

array([[ 31.06849839,  10.28132709,  13.07969446],
       [  9.03825754,  10.51117948,   0.80681955],
       [ -4.48076983,  10.05965349, -16.18168244]])

### 3. Dengan seed = 101, buatkan angka random sesuai dengan solusi di soal no. 2

In [4]:
# ketik kode kalian di dalam cel ini
# 1. buat random seed untuk mengunci data
np.random.seed(101)
# buat angka random sesuai nomor 2
np.random.normal(loc=4, scale=10, size=(3,3))

array([[ 31.06849839,  10.28132709,  13.07969446],
       [  9.03825754,  10.51117948,   0.80681955],
       [ -4.48076983,  10.05965349, -16.18168244]])

In [ ]:
# hasil output yang diinginkan:

array([[ 31.06849839,  10.28132709,  13.07969446],
       [  9.03825754,  10.51117948,   0.80681955],
       [ -4.48076983,  10.05965349, -16.18168244]])